name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: employee-app
          path: target/*.jar

      - name: Run Application (CD Simulation)
        run: |
          echo "Starting application..."
          java -jar target/*.jar &
          sleep 15

          echo "Printing logs..."
          cat app.log || true

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: application-logs
          path: app.log
